- name: Retrieve Trillian transparency log source code
  shell:  "go get -t -u -v github.com/google/trillian"

- name: Install Trillian server
  shell:  "go install ./trillian_log_server"
  args:
    chdir: "$HOME/go/src/github.com/google/trillian/cmd/"

- name: Install Trillian signer
  shell:  "go build ./trillian_log_signer"
  args:
    chdir: "$HOME/go/src/github.com/google/trillian/cmd/"
