---
- name: Retrieve Trillian transparency log source code
  shell: "go get -t -u github.com/google/trillian"

- name: Build Trillian server
  shell: "go install ./trillian_log_server"
  args:
    chdir: "$HOME/go/src/github.com/google/trillian/cmd/"

- name: Install Trillian server
  ansible.builtin.copy:
    # copy works with ~ but not $HOME, not sure why
    src: "~/go/bin/trillian_log_server"
    dest: "/usr/local/bin/"

- name: Build Trillian signer
  shell: "go install ./trillian_log_signer"
  args:
    chdir: "$HOME/go/src/github.com/google/trillian/cmd/"

- name: Install Trillian signer
  ansible.builtin.copy:
    src: "~/go/bin/trillian_log_signer"
    dest: "/usr/local/bin/"
