---
- hosts: all, localhost
  become: true
  tasks:
    - name: Set eth0 MTU to 1420, to avoid api.bitbucket.org TLS timeout
      command: "ip link set dev eth0 mtu 1420"

       # Rekor relies on Trillian log server, which in turn relies or a MySQL
       # database. If you have any of these already running, feel free to
       # disable the role. Redis is optional but recommended if you want to be
       # able to make fast queries on rekor-server. Furthermore, you'll have to
       # start rekor-server with the `--enable_retrieve_api=false` option.

    - include_role:
        name: mariadb

        #    - name: Ensure MariaDB is running and listening
        #      command: "nc -vz localhost 3306"
        #      retries: 5
        #      delay: 10

        # - name: Test bla
        #   command: systemctl status mysql
        #   register: mysql_status
        #   failed_when: "'not' in mysql_status.stdout"

     #- name: Update repositories (RHEL, CentOS, Fedora)
     #  dnf:  update_cache=yes
     #  when: ansible_distribution == "Fedora" or ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

     #- name: Update repositories (Debian, Ubuntu)
     #  apt: update_cache=yes
     #  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"

    - include_role:
       name: redis

    - include_role:
        name: trillian-log-server

    - include_role:
        name: rekor
