- name: Check for rekor server source code presence
  stat:
    path: "$HOME/go/src/github.com/sigstore/rekor/cmd/server"
  register: has_rekor_server_code

- name: Donwload rekor server source code
  command: "go get -u -t github.com/sigstore/rekor/cmd/server"
  ignore_errors: yes
  when: not has_rekor_server_code.stat.exists

- name: Check if we have already built rekor server
  stat:
    path: "$HOME/go/src/github.com/sigstore/rekor/cmd/server/rekor-server"
  register: has_rekor_server

- name: Build rekor server
  command: "go build -o rekor-server"
  args:
    chdir: "$HOME/go/src/github.com/sigstore/rekor/cmd/server/"
  when: not has_rekor_server.stat.exists

- name: Check if we have already installed rekor server
  stat:
    path: "/usr/local/bin/rekor-server"
  register: has_rekor_server_installed

- name: Install rekor server
  ansible.builtin.copy:
    src: "~/go/src/github.com/sigstore/rekor/cmd/server/rekor-server"
    dest: "/usr/local/bin/"
    remote_src: yes
    mode: u=rwx,g=rx,o=x
  when: not has_rekor_server_installed.stat.exists

#- name: Start rekor server
#  command: "rekor-server serve"
