---
- name: Install mariadb-server
  dnf:
    state: present
    name: mariadb-server

    #- name: Enable MariaDB systemd service
    #  ansible.builtin.systemd:
    #    state: enabled
    #    name: mariadb

- name: Enable and start MariaDB systemd service
  ansible.builtin.systemd:
    state: started
    enabled: yes
    name: mariadb
